### ISSUE TITLE
Can we use this version to use another shell in VS Code?

### ISSUE THREAD

**Issue by amyspark** [git-for-windows/git-sdk-64#17] opened 2019-10-25 17:26 UTC
Hey,

As I wanted to use the Fish shell in Git Bash, I switched to this SDK version.  I cannot find out if there's a helper to set up a MSYS2 shell, like `bin/bash.exe` in the standard Git for Windows installation.

Another different problem is that there is no way to change the default shell, as `git-bash.exe` hardcodes the login shell to Bash.

Can you help out with this?

**Comment by PhilipOakley** [comment] 2019-10-25 21:10
https://github.com/git-for-windows/MINGW-packages/blob/e52f91ddc34cac7fcf7704b2c1948bf190373134/mingw-w64-git/git-wrapper.c#L510-L550

(from https://github.com/git-for-windows/git/pull/2357#issuecomment-543959154)

**Comment by dscho** [comment] 2019-10-28 15:23
>  I cannot find out if there's a helper to set up a MSYS2 shell, like `bin/bash.exe` in the standard Git for Windows installation.

You can use `edit-git-bash.exe` (in the SDK, call `sdk cd build-extra && make edit-git-bash.exe`) to edit the resources of `git-bash.exe`, which is how the installer [overrides the command-line](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss#L282-L304) e.g. to open a regular Windows Console rather than a MinTTY window. You can use the same to override which shell to run.

**Comment by amyspark** [comment] 2019-10-29 00:13
I followed @PhilipOakley 's comment and added `--cd-to-home -c fish` to my Git Bash shortcuts. To use it with VS Code, I copied the `bin/bash.exe` executable and added the same.

**Comment by dscho** [comment] 2019-10-29 14:02
So can we close this now? It was not a bug report, after all...

**Closed** 2020-04-17 17:07 UTC
